#!/usr/bin/env swift
//
// GenerateWordFrequency.swift — extract the single-character subset of a
// phrase-occurrence corpus into a per-character frequency table.
//
// Interface:
//   ./GenerateWordFrequency.swift <input> <output> <source-url>
//
// Reads <input> (`entry<space>count` per line, the phrase.occ format), keeps
// only entries whose key is exactly one Unicode scalar, and writes them to
// <output> in the input's native order. <source-url> is embedded in the
// header for provenance. The result ranks individual characters (used, e.g.,
// to order wildcard query results).

import Foundation

let args = CommandLine.arguments
guard args.count == 4 else {
    let name = (args[0] as NSString).lastPathComponent
    FileHandle.standardError.write(Data("Usage: \(name) <input> <output> <source-url>\n".utf8))
    exit(2)
}

let inputPath = args[1]
let outputPath = args[2]
let sourceURL = args[3]

let inputData: String
do {
    inputData = try String(contentsOfFile: inputPath, encoding: .utf8)
} catch {
    FileHandle.standardError.write(Data("✗ Cannot read input \(inputPath): \(error)\n".utf8))
    exit(1)
}

var entries: [String] = []
for line in inputData.split(separator: "\n", omittingEmptySubsequences: true) {
    // phrase.occ separates entry and count by whitespace (tab or spaces).
    guard let separator = line.firstIndex(where: { $0.isWhitespace }) else { continue }
    let key = line[..<separator]
    guard key.unicodeScalars.count == 1 else { continue }
    let count = line[line.index(after: separator)...]
    entries.append("\(key)\t\(count)")
}

var outputLines: [String] = [
    "# Per-character frequency table (single-character subset of the source corpus).",
    "# format: char<TAB>count",
    "# source: \(sourceURL)",
    "# generated by Scripts/GenerateWordFrequency.swift via HandleExternalResources — DO NOT EDIT",
    "",
]
outputLines.append(contentsOf: entries)

let output = outputLines.joined(separator: "\n") + "\n"
do {
    try output.write(toFile: outputPath, atomically: true, encoding: .utf8)
} catch {
    FileHandle.standardError.write(Data("✗ Cannot write output \(outputPath): \(error)\n".utf8))
    exit(1)
}
FileHandle.standardError.write(Data("wrote \(entries.count) single-char frequencies\n".utf8))
