#!/usr/bin/env swift
//
// GenerateSymbolNames.swift — build the consolidated Traditional Chinese
// symbol-name table. Invoked by HandleExternalResources as a processor:
//
//   GenerateSymbolNames.swift <cldr-annotations.json> <output> <url>
//
// Uses CLDR zh-Hant annotations (BMP single-codepoint symbols → tts[0]) as the
// base, then overlays Scripts/SymbolNamesOverride.zh-Hant.txt (hand-maintained,
// wins on conflicts). Writes <output> as `symbol<TAB>name`, sorted by codepoint.
// The result is a reusable name table for any input method, not just Array.

import Foundation

let arguments = CommandLine.arguments
guard arguments.count == 4 else {
    FileHandle.standardError.write(
        Data("usage: \(arguments[0]) <cldr.json> <output> <url>\n".utf8))
    exit(2)
}
let inputPath = arguments[1]
let outputPath = arguments[2]
let sourceURL = arguments[3]

// The hand-curated override lives next to this script.
let scriptDir = URL(fileURLWithPath: arguments[0]).deletingLastPathComponent()
let overridePath = scriptDir
    .appendingPathComponent("SymbolNamesOverride.zh-Hant.txt").path

func readTSV(_ path: String) -> [String: String] {
    var names: [String: String] = [:]
    guard let text = try? String(contentsOfFile: path, encoding: .utf8) else { return names }
    for line in text.components(separatedBy: .newlines) {
        if line.isEmpty || line.hasPrefix("#") { continue }
        guard let tab = line.firstIndex(of: "\t") else { continue }
        names[String(line[..<tab])] = String(line[line.index(after: tab)...])
    }
    return names
}

// CLDR annotations JSON → { single BMP symbol : tts[0] }.
func readCLDR(_ path: String) -> [String: String] {
    var names: [String: String] = [:]
    guard let data = FileManager.default.contents(atPath: path),
        let root = try? JSONSerialization.jsonObject(with: data) as? [String: Any],
        let outer = root["annotations"] as? [String: Any],
        let annotations = outer["annotations"] as? [String: Any]
    else {
        FileHandle.standardError.write(Data("✗ cannot parse CLDR JSON: \(path)\n".utf8))
        return names
    }
    for (symbol, value) in annotations {
        let scalars = Array(symbol.unicodeScalars)
        guard scalars.count == 1, scalars[0].value <= 0xFFFF else { continue }
        if let entry = value as? [String: Any],
            let tts = entry["tts"] as? [String], let name = tts.first {
            names[symbol] = name
        }
    }
    return names
}

var merged = readCLDR(inputPath)                 // base
for (symbol, name) in readTSV(overridePath) {    // override wins
    merged[symbol] = name
}

func firstScalar(_ s: String) -> UInt32 { s.unicodeScalars.first?.value ?? 0 }
let sorted = merged.sorted { lhs, rhs in
    let a = firstScalar(lhs.key), b = firstScalar(rhs.key)
    return a != b ? a < b : lhs.key < rhs.key
}

var out = """
# Consolidated Traditional Chinese symbol names (reusable across input methods).
# format: symbol<TAB>name
# source: \(sourceURL) overlaid with Scripts/SymbolNamesOverride.zh-Hant.txt (override wins)
# generated by Scripts/GenerateSymbolNames.swift via HandleExternalResources — DO NOT EDIT

"""
out += "\n" + sorted.map { "\($0.key)\t\($0.value)" }.joined(separator: "\n") + "\n"

try out.write(toFile: outputPath, atomically: true, encoding: .utf8)
FileHandle.standardError.write(Data("wrote \(merged.count) names\n".utf8))
