#!/usr/bin/env swift
//
// GenerateAssociatedDictionary.swift — derive an associated-mode lookup table
// from a phrase-frequency corpus (McBopomofo's phrase.occ format).
//
// Interface:
//   ./GenerateAssociatedDictionary.swift <input> <output> <source-url>
//
// Reads <input> (`phrase<TAB>freq` per line), groups by leading character,
// deduplicates by the leading character of the remainder (keeping the
// highest-frequency variant), and writes the top 60 per prefix to <output>.
// <source-url> is embedded in the output header for provenance.

import Foundation

let args = CommandLine.arguments
guard args.count == 4 else {
    let name = (args[0] as NSString).lastPathComponent
    FileHandle.standardError.write(Data("Usage: \(name) <input> <output> <source-url>\n".utf8))
    exit(2)
}

let inputPath = args[1]
let outputPath = args[2]
let sourceURL = args[3]

let maxEntriesPerPrefix = 60

func isAllLetterOther(_ phrase: String) -> Bool {
    for scalar in phrase.unicodeScalars {
        if scalar.properties.generalCategory != .otherLetter {
            return false
        }
    }
    return !phrase.isEmpty
}

let inputData: String
do {
    inputData = try String(contentsOfFile: inputPath, encoding: .utf8)
} catch {
    FileHandle.standardError.write(Data("✗ Cannot read input \(inputPath): \(error)\n".utf8))
    exit(1)
}

var prefixMap: [Character: [(remainder: String, freq: Int)]] = [:]
for line in inputData.split(separator: "\n", omittingEmptySubsequences: true) {
    // phrase.occ separates phrase and frequency by whitespace (tab or spaces).
    let parts = line.split(whereSeparator: { $0.isWhitespace })
    guard parts.count == 2 else { continue }
    let phrase = String(parts[0])
    guard let freq = Int(parts[1]) else { continue }
    guard phrase.count >= 2, isAllLetterOther(phrase) else { continue }
    let first = phrase.first!
    let remainder = String(phrase.dropFirst())
    prefixMap[first, default: []].append((remainder, freq))
}

var outputLines: [String] = [
    "# Associated-phrase lookup table (leading character → following phrases).",
    "# format: leadingChar<TAB>phrase[<space>phrase...]",
    "# source: \(sourceURL)",
    "# generated by Scripts/GenerateAssociatedDictionary.swift via HandleExternalResources — DO NOT EDIT",
    "",
]

for prefix in prefixMap.keys.sorted() {
    let ranked = prefixMap[prefix]!.sorted { $0.freq > $1.freq }
    var seenLeading: Set<Character> = []
    var picked: [String] = []
    for entry in ranked {
        guard let leading = entry.remainder.first else { continue }
        if seenLeading.contains(leading) { continue }
        seenLeading.insert(leading)
        picked.append(entry.remainder)
        if picked.count >= maxEntriesPerPrefix { break }
    }
    if picked.isEmpty { continue }
    outputLines.append("\(prefix)\t\(picked.joined(separator: " "))")
}

let output = outputLines.joined(separator: "\n") + "\n"
do {
    try output.write(toFile: outputPath, atomically: true, encoding: .utf8)
} catch {
    FileHandle.standardError.write(Data("✗ Cannot write output \(outputPath): \(error)\n".utf8))
    exit(1)
}
