#!/usr/bin/env swift
//
// MarkRareByFontCoverage.swift — convert a .cin character table into a flat
// `code<TAB>char` table, appending a third column "1" to characters the
// macOS-bundled fonts can't render. Those are "rare" characters that need a
// matching font installed to display, which the engine hides by default.
//
// Interface (HandleExternalResources processor convention):
//   ./MarkRareByFontCoverage.swift <input.cin> <output.txt> <source-url> [section]
//
// "section" selects which block to emit from a cin / cin2 source:
//   chardef (default) — %chardef entries, excluding any nested %symboldef block,
//                       and dropping pure-digit codes (unreachable as compositions).
//   symboldef         — only the %symboldef block (symbol groups).
//
// The base font (checked first as a fast path) defaults to "PingFang TC";
// override it with the CIN_BASE_FONT environment variable.
//
// Coverage is judged ONLY against macOS-bundled fonts (anywhere under
// /System/Library/ — including Fonts/, Fonts/Supplemental/, the PingFang faces
// shipped inside FontServices.framework, and the on-demand assets under
// AssetsV2/, plus the hidden system UI font). This keeps the flag portable: it
// reflects what a stock macOS can render, independent of any third-party fonts
// installed on the build machine. The LastResort placeholder font is excluded.
//
// Only the selected section's entries are emitted; other cin fields (%keyname,
// %selkey, …) are dropped — the engine hardcodes them.
//
// Diagnostics (common / rare counts, font count) go to stderr.

import AppKit
import CoreText
import Foundation

let arguments = CommandLine.arguments
guard arguments.count == 4 || arguments.count == 5 else {
    let name = (arguments[0] as NSString).lastPathComponent
    FileHandle.standardError.write(
        Data("Usage: \(name) <input.cin> <output.txt> <source-url> [chardef|symboldef]\n".utf8))
    exit(2)
}
let inputPath = arguments[1]
let outputPath = arguments[2]
let sourceURL = arguments[3]
let section = arguments.count == 5 ? arguments[4] : "chardef"
guard section == "chardef" || section == "symboldef" else {
    FileHandle.standardError.write(Data("✗ Unknown section '\(section)' (chardef|symboldef)\n".utf8))
    exit(2)
}
let baseFontName = ProcessInfo.processInfo.environment["CIN_BASE_FONT"] ?? "PingFang TC"

// Character sets to test against: the base font first (fast path for the common
// script), then every other macOS-bundled face. A font's character set is its
// self-reported coverage; membership testing is far cheaper than laying out and
// inspecting each value with CTLine.
let systemFontsRoot = "/System/Library/"
let baseFont = CTFontCreateWithName(baseFontName as CFString, 16, nil)
var charsets: [CFCharacterSet] = [CTFontCopyCharacterSet(baseFont)]

// The hidden system UI font (e.g. .SFNS) is excluded from the available-fonts
// collection but is present on every macOS and covers some symbols; add it
// explicitly via the proper API so those symbols aren't falsely flagged.
if let systemUIFont = CTFontCreateUIFontForLanguage(.system, 16, nil) {
    charsets.append(CTFontCopyCharacterSet(systemUIFont))
}

let collection = CTFontCollectionCreateFromAvailableFonts(nil)
if let descriptors = CTFontCollectionCreateMatchingFontDescriptors(collection) as? [CTFontDescriptor] {
    for descriptor in descriptors {
        let font = CTFontCreateWithFontDescriptor(descriptor, 16, nil)
        if (CTFontCopyPostScriptName(font) as String).contains("LastResort") { continue }
        let path = (CTFontCopyAttribute(font, kCTFontURLAttribute) as? URL)?.path ?? ""
        guard path.hasPrefix(systemFontsRoot) else { continue }
        charsets.append(CTFontCopyCharacterSet(font))
    }
}

// Whether every scalar of `string` is covered by some bundled font. Memoized by
// value (many codes share characters).
var renderableCache: [String: Bool] = [:]

func isRenderable(_ string: String) -> Bool {
    if let cached = renderableCache[string] { return cached }
    let renderable = string.unicodeScalars.allSatisfy { scalar in
        charsets.contains { CFCharacterSetIsLongCharacterMember($0, scalar.value) }
    }
    renderableCache[string] = renderable
    return renderable
}

guard let input = try? String(contentsOfFile: inputPath, encoding: .utf8) else {
    FileHandle.standardError.write(Data("cannot read \(inputPath)\n".utf8))
    exit(1)
}

var outputLines: [String] = [
    "# Character table with rare characters (no bundled-font glyph) flagged.",
    "# format: code<TAB>char  (a rare character gets a trailing <TAB>*)",
    "# source: \(sourceURL)",
    "# generated by Scripts/MarkRareByFontCoverage.swift via HandleExternalResources — DO NOT EDIT",
    "",
]
// %symboldef nests in %chardef: chardef mode emits the outer entries, symboldef the inner.
var inChardef = false
var inSymboldef = false
var common = 0
var rare = 0

for rawLine in input.components(separatedBy: "\n") {
    let line = rawLine.hasSuffix("\r") ? String(rawLine.dropLast()) : rawLine
    let trimmed = line.trimmingCharacters(in: .whitespaces)

    if trimmed.hasPrefix("%") {
        if trimmed.hasPrefix("%chardef begin") { inChardef = true }
        else if trimmed.hasPrefix("%chardef end") { inChardef = false }
        else if trimmed.hasPrefix("%symboldef begin") { inSymboldef = true }
        else if trimmed.hasPrefix("%symboldef end") { inSymboldef = false }
        continue
    }
    let active = section == "symboldef" ? inSymboldef : (inChardef && !inSymboldef)
    if !active || trimmed.isEmpty || trimmed.hasPrefix("#") { continue }

    let parts = line.split(separator: "\t", maxSplits: 1, omittingEmptySubsequences: false)
    guard parts.count == 2, !parts[1].isEmpty else { continue }
    let code = String(parts[0])
    let value = String(parts[1])
    // Pure-digit codes (e.g. `1` → `1`) aren't reachable as compositions; drop them.
    if section == "chardef" && code.allSatisfy(\.isNumber) { continue }
    if isRenderable(value) {
        outputLines.append("\(code)\t\(value)")
        common += 1
    } else {
        outputLines.append("\(code)\t\(value)\t*")
        rare += 1
    }
}

let output = outputLines.joined(separator: "\n") + "\n"
try output.write(toFile: outputPath, atomically: true, encoding: .utf8)

let err = FileHandle.standardError
err.write(Data("bundled fonts tested: \(charsets.count)\n".utf8))
err.write(Data("common: \(common)  rare: \(rare)\n".utf8))
